version: '3.8'


services:
  python-app-dev:
    build:
      context: .
      dockerfile: docker/dockerfile
    volumes:
      - .:/app
    working_dir: /app
    stdin_open: true
    tty: true
    command: tail -f /dev/null
    profiles:
      - dev
  python-app-work:
    build:
      context: .
      dockerfile: docker/work/dockerfile
    volumes:
      - .:/app
    working_dir: /app
    stdin_open: true
    tty: true
    command: tail -f /dev/null
    profiles:
      - work